### ISSUE TITLE
waybar/pulseaudio-slider bar does not show up. 

### ISSUE THREAD

**Issue by ghost** [jemhv/hypr-dune#1]
```
(waybar:39410): Gtk-WARNING **: 11:48:52.263: for_size smaller than min-size (0 < 1) while measuring gadget (node highlight, owner gtkmm__GtkScale)
[2024-04-15 11:48:52.321] [info] Bar configured (width: 1920, height: 58) for output: eDP-1
```

this is the error it shows in the terminal. 

I think it's some issue with waybar height, but I'm not sure how to fix the height.

**Comment by jemhv** [comment]
Should be solved now. Your computer for some reason wasn't getting the height automatically, so adding it manually is a good choice, do not know why mine was doing it correct while yours not, but give it a try. I hope it's going to be ok now.

**Comment by ghost** [comment]
Yeah it's solved now. :3rd_place_medal:
